# Generated by Django 5.1.5 on 2025-01-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=15),
            preserve_default=False,
        ),
    ]
