# Generated by Django 5.1.5 on 2025-01-28 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[(None, 'Select'), ('sts-1', 'Pending'), ('sts-2', 'Delivered'), ('sts-3', 'Cancelled'), ('sts-4', 'No Stock')], default='Pending', max_length=15, null=True, verbose_name='Order Status'),
        ),
    ]
